# Generated by Django 6.0.5 on 2026-05-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_value", models.TextField()),
                ("new_value", models.TextField()),
                ("changed_by", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emission_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emissions.emissionrecord",
                    ),
                ),
            ],
        ),
    ]
